name: Sync upstream (mirror)
on:
  schedule:
    - cron: "0 */6 * * *"   # toutes les 6h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/digibooms25/n8n-docs-complete.git
          git fetch upstream principal

      - name: Sync branch
        run: |
          # côté fork : branche 'main'
          git checkout main
          # côté upstream : branche 'principal'
          git pull upstream principal
          git push origin main
